name: Request official release
on:
  push:
    branches: [main]
permissions: {}
jobs:
  dispatch:
    uses: susanbeasles/workflow_depot/.github/workflows/request-release.yml@a99e0fe6a66ebffbcd33ca9921b53e0b069fc202
    secrets:
      RELEASE_DISPATCH_TOKEN: ${{ secrets.RELEASE_DISPATCH_TOKEN }}
